name: Pipes

on:
    pull_request:
        branches:
            - master
        paths:
            - 'composer.json'
            - '.github/**'
            - 'src/**'
            - 'tests/**'

jobs:
    php81:
        name: PHP 8.1
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php80-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php80-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run checks
                run: composer run check
    php82:
        name: PHP 8.2
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php80-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php80-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run checks
                run: composer run check
    php83:
        name: PHP 8.3
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php80-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php80-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run checks
                run: composer run check
    php84:
        name: PHP 8.4
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php80-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php80-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run checks
                run: composer run check
